# Generated by Django 4.2.5 on 2024-07-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryattempt',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='сообщение об ошибке'),
        ),
    ]
