# Generated by Django 4.2.5 on 2024-07-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["email"],
                "permissions": [
                    ("can_view_users", "Can view users"),
                    ("can_change_is_active", "Can change is_active status"),
                ],
                "verbose_name": "пользователь",
                "verbose_name_plural": "пользователи",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                blank=True, default=True, null=True, verbose_name="статус пользователя"
            ),
        ),
    ]
