# Generated by Django 4.2.5 on 2024-07-21 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_client_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "ordering": ["full_name"],
                "verbose_name": "клиент",
                "verbose_name_plural": "клиенты",
            },
        ),
    ]
