# Generated by Django 4.2.5 on 2024-07-10 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0005_remove_mailing_send_time_mailing_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('created', 'Создана'), ('started', 'Запущена'), ('completed', 'Завершена'), ('canceled', 'Отменена')], default='created', max_length=20, verbose_name='статус'),
        ),
    ]
