# Generated by Django 4.2.5 on 2024-07-10 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0006_alter_mailing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='название рассылки'),
        ),
    ]
