# Generated by Django 4.2.5 on 2024-07-21 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0011_alter_mailing_options_alter_message_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="body",
            field=models.TextField(verbose_name="сообщение"),
        ),
        migrations.AlterField(
            model_name="message",
            name="subject",
            field=models.CharField(max_length=255, verbose_name="тема сообщения"),
        ),
    ]
