# Generated by Django 4.2.5 on 2024-07-26 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0012_alter_message_body_alter_message_subject"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["name"],
                "permissions": [
                    ("can_show_mailings", "Can show mailings"),
                    ("can_change_status", "Can change mailing status"),
                ],
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
            },
        ),
    ]
